name: CI
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    types: [edited, ready_for_review, opened, synchronize, reopened]
    paths-ignore:
      - 'site/**'
      - '**/*.md'

env:
  CYPRESS_VERIFY_TIMEOUT: 180000 # https://docs.cypress.io/guides/guides/command-line#cypress-verify
  CVAT_VERSION: "local"

jobs:
  no_run_on_description_changes:
    runs-on: ubuntu-latest
    if: github.event.action == 'edited' and github.event.changes.title == ''
    steps:
      - name: Step
        run: |
          echo hello
